### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by musiclover382**

### CODE REVIEW

**Comment by rafatosta** [comment]
Thank you very much for your collaboration, will be merged soon. I'm currently working with the spell checker, if you have the .bdir from Italy, please send it. Follow the dev branch

**Comment by musiclover382** [comment]
Hmmm, I'd like to help. I'm not sure I understand what the .bdir file is and how to get it though.

**Comment by rafatosta** [comment]
Everything is fine. I'm still doing it, but if I need help with Italian, I know who to talk to!

**Comment by rafatosta** [comment]
Hi!
There are new fields available for translation.
It seems that this week we will have a great update to be released.
Thanks for the collaboration.

**Comment by musiclover382** [comment]
I see, I won’t be home for a while and I don’t have access to my pc so it will take long for me to translate strings :P

**Comment by musiclover382** [comment]
Ok, I managed to translate the strings. I opened a PR

**Pull request closed without merging**
