### PR TITLE
show simpler icons on the system tray

### PR DESCRIPTION
**Pull request by Richardsause**
the two major linux desktop environments use symbolic icons on their trays, i would like zapzap to do the same(or similar) so im making this pull request, the icon isnt really symbolic but its a step towards that direction

### CODE REVIEW

**Comment by Richardsause** [comment]
Screenshot_20220515_204151
zapzap with kde icons on the tray

**Comment by Richardsause** [comment]
also ideally this would be with the other icons on the assets/stylesheets folder with a dark and light variant, but i dont really know how to make that work

**Comment by rafatosta** [comment]
I liked the solution, but I will not accept it because of the Gnome inconsistency. 
I will bring these icons as a form of customization in the settings. Thus, the user will be able to choose the type of icon he wants.
Thank you very much for the contribution!

**Comment by rafatosta** [comment]
I will release on the 2.6 branch. Could you test it locally from the source code execution and verify that it works correctly?

image

**Pull request closed without merging**
